# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2
import registry_pb2 as registry__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceNodeStub(object):
    """Service exposed by each inference node in the pipeline.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Forward = channel.unary_unary(
                '/unfed.InferenceNode/Forward',
                request_serializer=inference__pb2.ForwardRequest.SerializeToString,
                response_deserializer=inference__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.GetShard = channel.unary_stream(
                '/unfed.InferenceNode/GetShard',
                request_serializer=inference__pb2.GetShardRequest.SerializeToString,
                response_deserializer=inference__pb2.ShardChunk.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/unfed.InferenceNode/Commit',
                request_serializer=inference__pb2.CommitRequest.SerializeToString,
                response_deserializer=inference__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.GossipBlock = channel.unary_unary(
                '/unfed.InferenceNode/GossipBlock',
                request_serializer=inference__pb2.BlockMessage.SerializeToString,
                response_deserializer=inference__pb2.GossipResponse.FromString,
                _registered_method=True)
        self.GetBlocks = channel.unary_unary(
                '/unfed.InferenceNode/GetBlocks',
                request_serializer=inference__pb2.GetBlocksRequest.SerializeToString,
                response_deserializer=inference__pb2.GetBlocksResponse.FromString,
                _registered_method=True)
        self.SubmitShares = channel.unary_unary(
                '/unfed.InferenceNode/SubmitShares',
                request_serializer=inference__pb2.SubmitSharesRequest.SerializeToString,
                response_deserializer=inference__pb2.SubmitSharesResponse.FromString,
                _registered_method=True)
        self.SubscribeBlocks = channel.unary_stream(
                '/unfed.InferenceNode/SubscribeBlocks',
                request_serializer=inference__pb2.SubscribeBlocksRequest.SerializeToString,
                response_deserializer=inference__pb2.BlockMessage.FromString,
                _registered_method=True)
        self.GetFeeEstimate = channel.unary_unary(
                '/unfed.InferenceNode/GetFeeEstimate',
                request_serializer=inference__pb2.FeeEstimateRequest.SerializeToString,
                response_deserializer=inference__pb2.FeeEstimateResponse.FromString,
                _registered_method=True)
        self.VerifyCapacity = channel.unary_unary(
                '/unfed.InferenceNode/VerifyCapacity',
                request_serializer=registry__pb2.VerifyCapacityRequest.SerializeToString,
                response_deserializer=registry__pb2.VerifyCapacityResponse.FromString,
                _registered_method=True)


class InferenceNodeServicer(object):
    """Service exposed by each inference node in the pipeline.
    """

    def Forward(self, request, context):
        """Forward pass: receives an activation tensor (or token IDs for the first node),
        runs through this node's layers, and returns the result.
        For intermediate nodes: returns the activation tensor for the next node.
        For the last node: returns the generated token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShard(self, request, context):
        """Transfer a shard file to a requesting node (BitTorrent-style P2P weight distribution).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Commit: compute forward pass and return only the output hash (for voting).
        The node holds the output in memory for a follow-up Forward call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GossipBlock(self, request, context):
        """Share-chain gossip: push a new block to this peer (daemon-to-daemon).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlocks(self, request, context):
        """Share-chain sync: request blocks from a given height onward.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitShares(self, request, context):
        """Submit compute shares to the daemon after each forward pass.
        Compute nodes call this instead of managing their own chain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeBlocks(self, request, context):
        """Subscribe to new blocks in real-time (server-stream, light-wallet mode).
        Returns historical blocks from from_height, then keeps streaming new ones.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeeEstimate(self, request, context):
        """Get the current fee estimate from the daemon's fee oracle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCapacity(self, request, context):
        """Capacity verification: registry challenges node to prove reported resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=inference__pb2.ForwardRequest.FromString,
                    response_serializer=inference__pb2.ForwardResponse.SerializeToString,
            ),
            'GetShard': grpc.unary_stream_rpc_method_handler(
                    servicer.GetShard,
                    request_deserializer=inference__pb2.GetShardRequest.FromString,
                    response_serializer=inference__pb2.ShardChunk.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=inference__pb2.CommitRequest.FromString,
                    response_serializer=inference__pb2.CommitResponse.SerializeToString,
            ),
            'GossipBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GossipBlock,
                    request_deserializer=inference__pb2.BlockMessage.FromString,
                    response_serializer=inference__pb2.GossipResponse.SerializeToString,
            ),
            'GetBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlocks,
                    request_deserializer=inference__pb2.GetBlocksRequest.FromString,
                    response_serializer=inference__pb2.GetBlocksResponse.SerializeToString,
            ),
            'SubmitShares': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitShares,
                    request_deserializer=inference__pb2.SubmitSharesRequest.FromString,
                    response_serializer=inference__pb2.SubmitSharesResponse.SerializeToString,
            ),
            'SubscribeBlocks': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeBlocks,
                    request_deserializer=inference__pb2.SubscribeBlocksRequest.FromString,
                    response_serializer=inference__pb2.BlockMessage.SerializeToString,
            ),
            'GetFeeEstimate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeeEstimate,
                    request_deserializer=inference__pb2.FeeEstimateRequest.FromString,
                    response_serializer=inference__pb2.FeeEstimateResponse.SerializeToString,
            ),
            'VerifyCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCapacity,
                    request_deserializer=registry__pb2.VerifyCapacityRequest.FromString,
                    response_serializer=registry__pb2.VerifyCapacityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unfed.InferenceNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('unfed.InferenceNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceNode(object):
    """Service exposed by each inference node in the pipeline.
    """

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.InferenceNode/Forward',
            inference__pb2.ForwardRequest.SerializeToString,
            inference__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/unfed.InferenceNode/GetShard',
            inference__pb2.GetShardRequest.SerializeToString,
            inference__pb2.ShardChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.InferenceNode/Commit',
            inference__pb2.CommitRequest.SerializeToString,
            inference__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GossipBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.InferenceNode/GossipBlock',
            inference__pb2.BlockMessage.SerializeToString,
            inference__pb2.GossipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.InferenceNode/GetBlocks',
            inference__pb2.GetBlocksRequest.SerializeToString,
            inference__pb2.GetBlocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitShares(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.InferenceNode/SubmitShares',
            inference__pb2.SubmitSharesRequest.SerializeToString,
            inference__pb2.SubmitSharesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/unfed.InferenceNode/SubscribeBlocks',
            inference__pb2.SubscribeBlocksRequest.SerializeToString,
            inference__pb2.BlockMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeeEstimate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.InferenceNode/GetFeeEstimate',
            inference__pb2.FeeEstimateRequest.SerializeToString,
            inference__pb2.FeeEstimateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.InferenceNode/VerifyCapacity',
            registry__pb2.VerifyCapacityRequest.SerializeToString,
            registry__pb2.VerifyCapacityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GuardRelayStub(object):
    """Guard relay service — lightweight relay between client and compute pipeline.
    The guard sees the client's IP but cannot read the encrypted request payload.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Relay = channel.unary_unary(
                '/unfed.GuardRelay/Relay',
                request_serializer=inference__pb2.RelayRequest.SerializeToString,
                response_deserializer=inference__pb2.RelayResponse.FromString,
                _registered_method=True)


class GuardRelayServicer(object):
    """Guard relay service — lightweight relay between client and compute pipeline.
    The guard sees the client's IP but cannot read the encrypted request payload.
    """

    def Relay(self, request, context):
        """Relay an encrypted request to a compute node and return the encrypted response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuardRelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Relay': grpc.unary_unary_rpc_method_handler(
                    servicer.Relay,
                    request_deserializer=inference__pb2.RelayRequest.FromString,
                    response_serializer=inference__pb2.RelayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unfed.GuardRelay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('unfed.GuardRelay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GuardRelay(object):
    """Guard relay service — lightweight relay between client and compute pipeline.
    The guard sees the client's IP but cannot read the encrypted request payload.
    """

    @staticmethod
    def Relay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.GuardRelay/Relay',
            inference__pb2.RelayRequest.SerializeToString,
            inference__pb2.RelayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MPCPeerStub(object):
    """--- MPC (2-party Beaver-triple-based secure computation for shard 0) ---

    Service for inter-MPC-node communication (Node A <-> Node B).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendShare = channel.unary_unary(
                '/unfed.MPCPeer/SendShare',
                request_serializer=inference__pb2.MPCSendShareRequest.SerializeToString,
                response_deserializer=inference__pb2.MPCSendShareResponse.FromString,
                _registered_method=True)
        self.Exchange = channel.unary_unary(
                '/unfed.MPCPeer/Exchange',
                request_serializer=inference__pb2.MPCExchangeRequest.SerializeToString,
                response_deserializer=inference__pb2.MPCExchangeResponse.FromString,
                _registered_method=True)
        self.CollectShare = channel.unary_unary(
                '/unfed.MPCPeer/CollectShare',
                request_serializer=inference__pb2.MPCCollectRequest.SerializeToString,
                response_deserializer=inference__pb2.MPCCollectResponse.FromString,
                _registered_method=True)
        self.OTBaseSetup = channel.unary_unary(
                '/unfed.MPCPeer/OTBaseSetup',
                request_serializer=inference__pb2.OTBaseSetupRequest.SerializeToString,
                response_deserializer=inference__pb2.OTBaseSetupResponse.FromString,
                _registered_method=True)
        self.OTExtend = channel.unary_unary(
                '/unfed.MPCPeer/OTExtend',
                request_serializer=inference__pb2.OTExtendRequest.SerializeToString,
                response_deserializer=inference__pb2.OTExtendResponse.FromString,
                _registered_method=True)


class MPCPeerServicer(object):
    """--- MPC (2-party Beaver-triple-based secure computation for shard 0) ---

    Service for inter-MPC-node communication (Node A <-> Node B).
    """

    def SendShare(self, request, context):
        """Send an embedding share and Beaver triple shares to the peer at the
        start of a session's MPC computation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exchange(self, request, context):
        """Exchange epsilon/delta values during a secure multiplication.
        Both parties call this simultaneously for each multiply operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectShare(self, request, context):
        """Signal peer to return its final share after layer 0 is complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OTBaseSetup(self, request, context):
        """OT-based Beaver triple generation: base OT setup round.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OTExtend(self, request, context):
        """OT-based Beaver triple generation: extension round.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MPCPeerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendShare': grpc.unary_unary_rpc_method_handler(
                    servicer.SendShare,
                    request_deserializer=inference__pb2.MPCSendShareRequest.FromString,
                    response_serializer=inference__pb2.MPCSendShareResponse.SerializeToString,
            ),
            'Exchange': grpc.unary_unary_rpc_method_handler(
                    servicer.Exchange,
                    request_deserializer=inference__pb2.MPCExchangeRequest.FromString,
                    response_serializer=inference__pb2.MPCExchangeResponse.SerializeToString,
            ),
            'CollectShare': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectShare,
                    request_deserializer=inference__pb2.MPCCollectRequest.FromString,
                    response_serializer=inference__pb2.MPCCollectResponse.SerializeToString,
            ),
            'OTBaseSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.OTBaseSetup,
                    request_deserializer=inference__pb2.OTBaseSetupRequest.FromString,
                    response_serializer=inference__pb2.OTBaseSetupResponse.SerializeToString,
            ),
            'OTExtend': grpc.unary_unary_rpc_method_handler(
                    servicer.OTExtend,
                    request_deserializer=inference__pb2.OTExtendRequest.FromString,
                    response_serializer=inference__pb2.OTExtendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unfed.MPCPeer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('unfed.MPCPeer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MPCPeer(object):
    """--- MPC (2-party Beaver-triple-based secure computation for shard 0) ---

    Service for inter-MPC-node communication (Node A <-> Node B).
    """

    @staticmethod
    def SendShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.MPCPeer/SendShare',
            inference__pb2.MPCSendShareRequest.SerializeToString,
            inference__pb2.MPCSendShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.MPCPeer/Exchange',
            inference__pb2.MPCExchangeRequest.SerializeToString,
            inference__pb2.MPCExchangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.MPCPeer/CollectShare',
            inference__pb2.MPCCollectRequest.SerializeToString,
            inference__pb2.MPCCollectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OTBaseSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.MPCPeer/OTBaseSetup',
            inference__pb2.OTBaseSetupRequest.SerializeToString,
            inference__pb2.OTBaseSetupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OTExtend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.MPCPeer/OTExtend',
            inference__pb2.OTExtendRequest.SerializeToString,
            inference__pb2.OTExtendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
