# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import registry_pb2 as registry__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistryStub(object):
    """Registry service — bootstrap node for peer discovery.
    Acts as a DNS seed: nodes register on startup, clients query to discover
    available nodes and build inference circuits.
    In production, multiple independent registries ensure no single point of failure.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/unfed.Registry/Register',
                request_serializer=registry__pb2.RegisterRequest.SerializeToString,
                response_deserializer=registry__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/unfed.Registry/Heartbeat',
                request_serializer=registry__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=registry__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/unfed.Registry/Unregister',
                request_serializer=registry__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=registry__pb2.UnregisterResponse.FromString,
                _registered_method=True)
        self.Discover = channel.unary_unary(
                '/unfed.Registry/Discover',
                request_serializer=registry__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=registry__pb2.DiscoverResponse.FromString,
                _registered_method=True)
        self.GetPoolHealth = channel.unary_unary(
                '/unfed.Registry/GetPoolHealth',
                request_serializer=registry__pb2.PoolHealthRequest.SerializeToString,
                response_deserializer=registry__pb2.PoolHealthResponse.FromString,
                _registered_method=True)
        self.SubmitTickets = channel.unary_unary(
                '/unfed.Registry/SubmitTickets',
                request_serializer=registry__pb2.SubmitTicketsRequest.SerializeToString,
                response_deserializer=registry__pb2.SubmitTicketsResponse.FromString,
                _registered_method=True)
        self.GetPendingTickets = channel.unary_unary(
                '/unfed.Registry/GetPendingTickets',
                request_serializer=registry__pb2.GetPendingTicketsRequest.SerializeToString,
                response_deserializer=registry__pb2.GetPendingTicketsResponse.FromString,
                _registered_method=True)
        self.SubmitFraudProof = channel.unary_unary(
                '/unfed.Registry/SubmitFraudProof',
                request_serializer=registry__pb2.FraudProofMessage.SerializeToString,
                response_deserializer=registry__pb2.FraudProofResponse.FromString,
                _registered_method=True)
        self.GetFraudProofs = channel.unary_unary(
                '/unfed.Registry/GetFraudProofs',
                request_serializer=registry__pb2.GetFraudProofsRequest.SerializeToString,
                response_deserializer=registry__pb2.GetFraudProofsResponse.FromString,
                _registered_method=True)
        self.GetManifest = channel.unary_unary(
                '/unfed.Registry/GetManifest',
                request_serializer=registry__pb2.GetManifestRequest.SerializeToString,
                response_deserializer=registry__pb2.GetManifestResponse.FromString,
                _registered_method=True)
        self.PutManifest = channel.unary_unary(
                '/unfed.Registry/PutManifest',
                request_serializer=registry__pb2.PutManifestRequest.SerializeToString,
                response_deserializer=registry__pb2.PutManifestResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/unfed.Registry/ListModels',
                request_serializer=registry__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=registry__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.GetPoolConfig = channel.unary_unary(
                '/unfed.Registry/GetPoolConfig',
                request_serializer=registry__pb2.GetPoolConfigRequest.SerializeToString,
                response_deserializer=registry__pb2.GetPoolConfigResponse.FromString,
                _registered_method=True)
        self.PutPoolConfig = channel.unary_unary(
                '/unfed.Registry/PutPoolConfig',
                request_serializer=registry__pb2.PutPoolConfigRequest.SerializeToString,
                response_deserializer=registry__pb2.PutPoolConfigResponse.FromString,
                _registered_method=True)
        self.GetClusterInfo = channel.unary_unary(
                '/unfed.Registry/GetClusterInfo',
                request_serializer=registry__pb2.GetClusterInfoRequest.SerializeToString,
                response_deserializer=registry__pb2.ClusterInfoResponse.FromString,
                _registered_method=True)
        self.SetClusterConfig = channel.unary_unary(
                '/unfed.Registry/SetClusterConfig',
                request_serializer=registry__pb2.SetClusterConfigRequest.SerializeToString,
                response_deserializer=registry__pb2.SetClusterConfigResponse.FromString,
                _registered_method=True)
        self.ExchangePeers = channel.unary_unary(
                '/unfed.Registry/ExchangePeers',
                request_serializer=registry__pb2.ExchangePeersRequest.SerializeToString,
                response_deserializer=registry__pb2.ExchangePeersResponse.FromString,
                _registered_method=True)
        self.GetPricing = channel.unary_unary(
                '/unfed.Registry/GetPricing',
                request_serializer=registry__pb2.GetPricingRequest.SerializeToString,
                response_deserializer=registry__pb2.GetPricingResponse.FromString,
                _registered_method=True)
        self.ReportUsage = channel.unary_unary(
                '/unfed.Registry/ReportUsage',
                request_serializer=registry__pb2.ReportUsageRequest.SerializeToString,
                response_deserializer=registry__pb2.ReportUsageResponse.FromString,
                _registered_method=True)
        self.RequestAssignment = channel.unary_unary(
                '/unfed.Registry/RequestAssignment',
                request_serializer=registry__pb2.RequestAssignmentRequest.SerializeToString,
                response_deserializer=registry__pb2.RequestAssignmentResponse.FromString,
                _registered_method=True)


class RegistryServicer(object):
    """Registry service — bootstrap node for peer discovery.
    Acts as a DNS seed: nodes register on startup, clients query to discover
    available nodes and build inference circuits.
    In production, multiple independent registries ensure no single point of failure.
    """

    def Register(self, request, context):
        """Register a node with the registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Periodic heartbeat to signal the node is still alive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Unregister a node (graceful shutdown).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Discover(self, request, context):
        """Discover available nodes, optionally filtered by model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoolHealth(self, request, context):
        """Get pool health: which shards are covered, node counts per shard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTickets(self, request, context):
        """Submit verification tickets collected by nodes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingTickets(self, request, context):
        """Get pending verification tickets (for verifier nodes to process).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitFraudProof(self, request, context):
        """Submit fraud proofs discovered by verifiers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFraudProofs(self, request, context):
        """Get all known fraud proofs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManifest(self, request, context):
        """Get model manifest (so new nodes can discover shards without out-of-band distribution).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutManifest(self, request, context):
        """Upload/update a model manifest (called by splitter or seed node).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List all models known to this registry with health summaries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoolConfig(self, request, context):
        """Get per-model economic rules (staking, rewards, fees).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutPoolConfig(self, request, context):
        """Publish/update per-model economic rules.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterInfo(self, request, context):
        """--- Cluster identity & gossip ---

        Get this cluster's identity, default economics, and live stats.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetClusterConfig(self, request, context):
        """Update the cluster config at runtime (operator use).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangePeers(self, request, context):
        """Gossip: exchange known peer registries for decentralized discovery.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPricing(self, request, context):
        """--- Pricing ---

        Get per-token pricing for a model (or cluster defaults).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportUsage(self, request, context):
        """Report token usage after a generation request (for settlement accounting).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAssignment(self, request, context):
        """--- Auto-assignment ---

        Request a role/shard assignment from the registry based on hardware capacity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=registry__pb2.RegisterRequest.FromString,
                    response_serializer=registry__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=registry__pb2.HeartbeatRequest.FromString,
                    response_serializer=registry__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=registry__pb2.UnregisterRequest.FromString,
                    response_serializer=registry__pb2.UnregisterResponse.SerializeToString,
            ),
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=registry__pb2.DiscoverRequest.FromString,
                    response_serializer=registry__pb2.DiscoverResponse.SerializeToString,
            ),
            'GetPoolHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoolHealth,
                    request_deserializer=registry__pb2.PoolHealthRequest.FromString,
                    response_serializer=registry__pb2.PoolHealthResponse.SerializeToString,
            ),
            'SubmitTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTickets,
                    request_deserializer=registry__pb2.SubmitTicketsRequest.FromString,
                    response_serializer=registry__pb2.SubmitTicketsResponse.SerializeToString,
            ),
            'GetPendingTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingTickets,
                    request_deserializer=registry__pb2.GetPendingTicketsRequest.FromString,
                    response_serializer=registry__pb2.GetPendingTicketsResponse.SerializeToString,
            ),
            'SubmitFraudProof': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitFraudProof,
                    request_deserializer=registry__pb2.FraudProofMessage.FromString,
                    response_serializer=registry__pb2.FraudProofResponse.SerializeToString,
            ),
            'GetFraudProofs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFraudProofs,
                    request_deserializer=registry__pb2.GetFraudProofsRequest.FromString,
                    response_serializer=registry__pb2.GetFraudProofsResponse.SerializeToString,
            ),
            'GetManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManifest,
                    request_deserializer=registry__pb2.GetManifestRequest.FromString,
                    response_serializer=registry__pb2.GetManifestResponse.SerializeToString,
            ),
            'PutManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.PutManifest,
                    request_deserializer=registry__pb2.PutManifestRequest.FromString,
                    response_serializer=registry__pb2.PutManifestResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=registry__pb2.ListModelsRequest.FromString,
                    response_serializer=registry__pb2.ListModelsResponse.SerializeToString,
            ),
            'GetPoolConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoolConfig,
                    request_deserializer=registry__pb2.GetPoolConfigRequest.FromString,
                    response_serializer=registry__pb2.GetPoolConfigResponse.SerializeToString,
            ),
            'PutPoolConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.PutPoolConfig,
                    request_deserializer=registry__pb2.PutPoolConfigRequest.FromString,
                    response_serializer=registry__pb2.PutPoolConfigResponse.SerializeToString,
            ),
            'GetClusterInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterInfo,
                    request_deserializer=registry__pb2.GetClusterInfoRequest.FromString,
                    response_serializer=registry__pb2.ClusterInfoResponse.SerializeToString,
            ),
            'SetClusterConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetClusterConfig,
                    request_deserializer=registry__pb2.SetClusterConfigRequest.FromString,
                    response_serializer=registry__pb2.SetClusterConfigResponse.SerializeToString,
            ),
            'ExchangePeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangePeers,
                    request_deserializer=registry__pb2.ExchangePeersRequest.FromString,
                    response_serializer=registry__pb2.ExchangePeersResponse.SerializeToString,
            ),
            'GetPricing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPricing,
                    request_deserializer=registry__pb2.GetPricingRequest.FromString,
                    response_serializer=registry__pb2.GetPricingResponse.SerializeToString,
            ),
            'ReportUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportUsage,
                    request_deserializer=registry__pb2.ReportUsageRequest.FromString,
                    response_serializer=registry__pb2.ReportUsageResponse.SerializeToString,
            ),
            'RequestAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAssignment,
                    request_deserializer=registry__pb2.RequestAssignmentRequest.FromString,
                    response_serializer=registry__pb2.RequestAssignmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unfed.Registry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('unfed.Registry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Registry(object):
    """Registry service — bootstrap node for peer discovery.
    Acts as a DNS seed: nodes register on startup, clients query to discover
    available nodes and build inference circuits.
    In production, multiple independent registries ensure no single point of failure.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/Register',
            registry__pb2.RegisterRequest.SerializeToString,
            registry__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/Heartbeat',
            registry__pb2.HeartbeatRequest.SerializeToString,
            registry__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/Unregister',
            registry__pb2.UnregisterRequest.SerializeToString,
            registry__pb2.UnregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/Discover',
            registry__pb2.DiscoverRequest.SerializeToString,
            registry__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoolHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/GetPoolHealth',
            registry__pb2.PoolHealthRequest.SerializeToString,
            registry__pb2.PoolHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/SubmitTickets',
            registry__pb2.SubmitTicketsRequest.SerializeToString,
            registry__pb2.SubmitTicketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/GetPendingTickets',
            registry__pb2.GetPendingTicketsRequest.SerializeToString,
            registry__pb2.GetPendingTicketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitFraudProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/SubmitFraudProof',
            registry__pb2.FraudProofMessage.SerializeToString,
            registry__pb2.FraudProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFraudProofs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/GetFraudProofs',
            registry__pb2.GetFraudProofsRequest.SerializeToString,
            registry__pb2.GetFraudProofsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/GetManifest',
            registry__pb2.GetManifestRequest.SerializeToString,
            registry__pb2.GetManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/PutManifest',
            registry__pb2.PutManifestRequest.SerializeToString,
            registry__pb2.PutManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/ListModels',
            registry__pb2.ListModelsRequest.SerializeToString,
            registry__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoolConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/GetPoolConfig',
            registry__pb2.GetPoolConfigRequest.SerializeToString,
            registry__pb2.GetPoolConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutPoolConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/PutPoolConfig',
            registry__pb2.PutPoolConfigRequest.SerializeToString,
            registry__pb2.PutPoolConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/GetClusterInfo',
            registry__pb2.GetClusterInfoRequest.SerializeToString,
            registry__pb2.ClusterInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetClusterConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/SetClusterConfig',
            registry__pb2.SetClusterConfigRequest.SerializeToString,
            registry__pb2.SetClusterConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangePeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/ExchangePeers',
            registry__pb2.ExchangePeersRequest.SerializeToString,
            registry__pb2.ExchangePeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPricing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/GetPricing',
            registry__pb2.GetPricingRequest.SerializeToString,
            registry__pb2.GetPricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/ReportUsage',
            registry__pb2.ReportUsageRequest.SerializeToString,
            registry__pb2.ReportUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unfed.Registry/RequestAssignment',
            registry__pb2.RequestAssignmentRequest.SerializeToString,
            registry__pb2.RequestAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
