#!/usr/bin/env bash
# -------------------------------------------------------------------
# Deploy UNFED contracts to a public testnet (Sepolia, Holesky, etc.)
#
# Required env vars:
#   CHAIN_RPC_URL          — Testnet RPC (e.g. https://rpc.sepolia.org)
#   OPERATOR_PRIVATE_KEY   — Deployer/operator wallet private key (funded with testnet ETH)
#   OPERATOR_ADDRESS       — Deployer/operator wallet address
#
# Usage:
#   export CHAIN_RPC_URL="https://rpc.sepolia.org"
#   export OPERATOR_PRIVATE_KEY="0x..."
#   export OPERATOR_ADDRESS="0x..."
#   ./scripts/deploy_testnet.sh
# -------------------------------------------------------------------
set -euo pipefail

: "${CHAIN_RPC_URL:?Error: CHAIN_RPC_URL env var required (e.g. https://rpc.sepolia.org)}"
: "${OPERATOR_PRIVATE_KEY:?Error: OPERATOR_PRIVATE_KEY env var required}"
: "${OPERATOR_ADDRESS:?Error: OPERATOR_ADDRESS env var required}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="${PROJECT_DIR}/contracts"
ENV_FILE="${PROJECT_DIR}/deployed.env"

export PATH="$HOME/.foundry/bin:$PATH"

echo "[deploy] Deploying to ${CHAIN_RPC_URL}..."
echo "[deploy] Operator: ${OPERATOR_ADDRESS}"

DEPLOY_OUTPUT=$(cd "$CONTRACTS_DIR" && PRIVATE_KEY="$OPERATOR_PRIVATE_KEY" \
    forge script script/Deploy.s.sol \
    --rpc-url "$CHAIN_RPC_URL" \
    --broadcast \
    --slow 2>&1)

TOKEN_ADDR=$(echo "$DEPLOY_OUTPUT" | grep "TOKEN_ADDRESS=" | sed 's/.*TOKEN_ADDRESS=//')
ESCROW_ADDR=$(echo "$DEPLOY_OUTPUT" | grep "ESCROW_ADDRESS=" | sed 's/.*ESCROW_ADDRESS=//')

if [ -z "$TOKEN_ADDR" ] || [ -z "$ESCROW_ADDR" ]; then
    echo "[deploy] ERROR: Failed to parse deployed addresses"
    echo "$DEPLOY_OUTPUT"
    exit 1
fi

cat > "$ENV_FILE" <<EOF
# UNFED AI — deployed contract addresses
# Generated by scripts/deploy_testnet.sh
CHAIN_RPC_URL=${CHAIN_RPC_URL}
TOKEN_ADDRESS=${TOKEN_ADDR}
ESCROW_ADDRESS=${ESCROW_ADDR}
OPERATOR_PRIVATE_KEY=${OPERATOR_PRIVATE_KEY}
OPERATOR_ADDRESS=${OPERATOR_ADDRESS}
EOF

echo "[deploy] Contracts deployed:"
echo "  Token:  ${TOKEN_ADDR}"
echo "  Escrow: ${ESCROW_ADDR}"
echo "  RPC:    ${CHAIN_RPC_URL}"
echo ""
echo "[deploy] Written to ${ENV_FILE}"
echo "[deploy] Start registry with:"
echo "  python -m network.registry_server --port 50050 --cluster-config cluster_config.json"
