#!/usr/bin/env bash
# -------------------------------------------------------------------
# Start a local Anvil chain and deploy the UNFED escrow contracts.
#
# Usage:
#   ./scripts/start_local_chain.sh          # default port 8545
#   ./scripts/start_local_chain.sh 8546     # custom port
#
# Output:
#   - Writes deployed addresses to contracts/deployed.env
#   - Anvil runs in the background (kill with: kill $(cat /tmp/anvil.pid))
# -------------------------------------------------------------------
set -euo pipefail

PORT="${1:-${UNFED_CHAIN_PORT:-8545}}"
NUM_ACCOUNTS="${UNFED_ANVIL_ACCOUNTS:-10}"
RPC_URL="http://localhost:${PORT}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="${UNFED_CONTRACTS_DIR:-${PROJECT_DIR}/contracts}"
ENV_FILE="${UNFED_DEPLOYED_ENV:-${PROJECT_DIR}/deployed.env}"
PID_FILE="${UNFED_ANVIL_PID_FILE:-/tmp/anvil.pid}"

export PATH="$HOME/.foundry/bin:$PATH"

# ---- 1. Start Anvil ------------------------------------------------
echo "[chain] Starting Anvil on port ${PORT} with ${NUM_ACCOUNTS} accounts..."
anvil --port "$PORT" --accounts "$NUM_ACCOUNTS" --silent &
ANVIL_PID=$!
echo "$ANVIL_PID" > "$PID_FILE"
sleep 2

if ! kill -0 "$ANVIL_PID" 2>/dev/null; then
    echo "[chain] ERROR: Anvil failed to start"
    exit 1
fi
echo "[chain] Anvil running (PID ${ANVIL_PID})"

# ---- 2. Deploy contracts -------------------------------------------
echo "[chain] Deploying contracts..."
DEPLOY_OUTPUT=$(cd "$CONTRACTS_DIR" && forge script script/Deploy.s.sol \
    --rpc-url "$RPC_URL" \
    --broadcast 2>&1)

# Parse deployed addresses from forge output
TOKEN_ADDR=$(echo "$DEPLOY_OUTPUT" | grep "TOKEN_ADDRESS=" | sed 's/.*TOKEN_ADDRESS=//')
ESCROW_ADDR=$(echo "$DEPLOY_OUTPUT" | grep "ESCROW_ADDRESS=" | sed 's/.*ESCROW_ADDRESS=//')

if [ -z "$TOKEN_ADDR" ] || [ -z "$ESCROW_ADDR" ]; then
    echo "[chain] ERROR: Failed to parse deployed addresses"
    echo "$DEPLOY_OUTPUT"
    kill "$ANVIL_PID" 2>/dev/null
    exit 1
fi

# ---- 3. Write env file ---------------------------------------------
# Operator key must be provided via environment (no hardcoded default).
# For local Anvil dev, export the default account 0 key before running:
#   export OPERATOR_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
#   export OPERATOR_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
: "${OPERATOR_PRIVATE_KEY:?Error: OPERATOR_PRIVATE_KEY env var required}"
: "${OPERATOR_ADDRESS:?Error: OPERATOR_ADDRESS env var required}"

cat > "$ENV_FILE" <<EOF
# Auto-generated by start_local_chain.sh — do not edit
CHAIN_RPC_URL=${RPC_URL}
TOKEN_ADDRESS=${TOKEN_ADDR}
ESCROW_ADDRESS=${ESCROW_ADDR}
OPERATOR_PRIVATE_KEY=${OPERATOR_PRIVATE_KEY}
OPERATOR_ADDRESS=${OPERATOR_ADDRESS}
EOF

echo "[chain] Deployed addresses written to ${ENV_FILE}"
echo "[chain]   Token:  ${TOKEN_ADDR}"
echo "[chain]   Escrow: ${ESCROW_ADDR}"
echo "[chain]   RPC:    ${RPC_URL}"
echo ""
echo "[chain] To stop: kill \$(cat $PID_FILE)"
